localResourcesDir: ${project.basedir}/src/main/resources
loggerNamePrefix: oauth2-resource
baseApiPath: api
applicationId: oauth2-resource
server.port: 8082
security.basic.enabled: false
enableSourceModificationApi: true

uaaLocation: ${AUTH_DOMAIN:http://localhost:8080/uaa}

spring.oauth2:
  client:
    clientId: oauth_showcase_authorization_code
    clientSecret: secret
    accessTokenUri: ${uaaLocation}/oauth/token
    userAuthorizationUri: ${uaaLocation}/oauth/authorize
  resource:
    jwt.keyUri: ${uaaLocation}/token_key
